import PDFDocument from "pdfkit";
import fs from "fs";

export const generateDealPDFBuffer = async (deal: any): Promise<Buffer> => {
  const doc = new PDFDocument();
  const chunks: any[] = [];

  // Collect PDF data into chunks
  doc.on("data", (chunk: any) => chunks.push(chunk));
  doc.on("end", () => {});

  // Title
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("Diamond Deal Summary", { align: "center" });
  doc.moveDown();

  // Deal Details
  doc.fontSize(14).font("Helvetica-Bold").text("Deal Details:");
  doc
    .fontSize(12)
    .font("Helvetica")
    .text(`Deal ID: ${deal.id || "N/A"}`);
  doc.text(`Buyer: ${deal.buyer || "N/A"}`);
  doc.text(`Seller: ${deal.seller || "N/A"}`);
  doc.text(`Amount: $${deal.amount || "N/A"}`);
  doc.text(`Status: ${deal.status || "N/A"}`);
  doc.text(`Date: ${new Date(deal.date || Date.now()).toLocaleString()}`);
  doc.moveDown();

  // Diamond Details
  if (deal.diamond) {
    doc.fontSize(14).font("Helvetica-Bold").text("Diamond Details:");
    doc
      .fontSize(12)
      .font("Helvetica")
      .text(`Shape: ${deal.diamond.shape || "N/A"}`);
    doc.text(`Carat: ${deal.diamond.carat || "N/A"}`);
    doc.text(`Color: ${deal.diamond.color || "N/A"}`);
    doc.text(`Clarity: ${deal.diamond.clarity || "N/A"}`);
    doc.text(`Lab: ${deal.diamond.lab || "N/A"}`);
    doc.text(`Certificate Number: ${deal.diamond.certificateNumber || "N/A"}`);
    doc.moveDown();
  }

  // Terms and Conditions
  doc.fontSize(14).font("Helvetica-Bold").text("Terms and Conditions:");
  doc
    .fontSize(12)
    .font("Helvetica")
    .text(deal.terms || "No terms and conditions provided.");
  doc.moveDown();

  // Footer
  doc
    .fontSize(10)
    .font("Helvetica-Oblique")
    .text("Generated by DiamondApp", { align: "center" });

  // Finalize the PDF
  doc.end();

  // Wait for the PDF to finish and return the buffer
  await new Promise((resolve) => doc.on("end", resolve));
  return Buffer.concat(chunks);
};

export const savePDF = async (deal: any) => {
  const pdfBuffer = await generateDealPDFBuffer(deal);

  // Return the file path or URL
  return pdfBuffer;
};
